# Generated by Django 6.0.3 on 2026-03-15 05:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailychecklistitem',
            name='checklist',
        ),
        migrations.AlterModelOptions(
            name='dailychecklistitem',
            options={'ordering': ('order',), 'verbose_name': 'Checklist Item', 'verbose_name_plural': 'Checklist Items'},
        ),
        migrations.RemoveField(
            model_name='dailychecklistitem',
            name='is_completed',
        ),
        migrations.AddField(
            model_name='dailychecklistitem',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='DailyChecklistEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True)),
                ('auto_id', models.PositiveIntegerField(blank=True, db_index=True, editable=False, null=True, unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_updated', models.DateTimeField(blank=True, editable=False, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date', models.DateField()),
                ('is_completed', models.BooleanField(default=False)),
                ('creator', models.ForeignKey(blank=True, editable=False, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator_%(app_label)s_%(class)s_objects', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='activity.dailychecklistitem')),
                ('updater', models.ForeignKey(blank=True, editable=False, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updater_%(app_label)s_%(class)s_objects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Daily Checklist Entry',
                'verbose_name_plural': 'Daily Checklist Entries',
                'ordering': ('date', 'item__order'),
            },
        ),
        migrations.DeleteModel(
            name='DailyChecklist',
        ),
        migrations.AddConstraint(
            model_name='dailychecklistentry',
            constraint=models.UniqueConstraint(fields=('item', 'date'), name='unique_entry_per_item_per_day'),
        ),
    ]
