# Generated by Django 6.0.3 on 2026-03-15 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_remove_dailychecklistitem_checklist_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='dailychecklistentry',
            name='unique_entry_per_item_per_day',
        ),
        migrations.AlterField(
            model_name='journal',
            name='mood',
            field=models.CharField(choices=[('great', 'Great'), ('good', 'Good'), ('neutral', 'Neutral'), ('bad', 'Bad'), ('terrible', 'Terribble')], default='neutral', max_length=20),
        ),
        migrations.AlterField(
            model_name='todo',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High')], default='normal', max_length=20),
        ),
        migrations.RemoveField(
            model_name='dailychecklistentry',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='dailychecklistentry',
            name='item',
        ),
        migrations.RemoveField(
            model_name='dailychecklistentry',
            name='updater',
        ),
        migrations.DeleteModel(
            name='DailyChecklistItem',
        ),
        migrations.DeleteModel(
            name='DailyChecklistEntry',
        ),
    ]
